version: '3'
services:
  redis: # Redis 부분.
    image: redis:6.0.5
    command: redis-server --requirepass changeme --port 6379
    container_name: redis6379
    hostname: redis6379
    restart: always
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - "6379:6379"
  infra-subway:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - /var/log/next-step/:/logs/
