name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    name: DEPLOY
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v1
      
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with: 
          java-version: 1.8

      - name: Gradle Permission
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Build Docker Image
        run: docker build -t deploy:0.0.1 .

      - name: Docker Run
        run: docker run -d -p 8080:8080 deploy-test:0.0.1



