name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    name: DEPLOY
    runs-on: ubuntu-latest
    strategy:
      matrix:
        redis-version: [ 4, 5, 6 ]

    steps:
      - name: Checkout submodules
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.SUB_MODULE_SECRET }}
          submodules: recursive

      - name: Start Redis v${{ matrix.redis-version }}
        uses: supercharge/redis-github-action@1.2.0
        with:
          redis-version: ${{ matrix.redis-version }}

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Gradle Permission
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build --exclude-task test

      - name: Build Docker Image
        run: docker build -t subway:0.0.1 .

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_NAME }}
          password: ${{ secrets.DOCKER_HUB_PW }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_NAME }}/infra-subway:latest